In [1]:
import pandas as pd

print(pd.__version__)

3.0.5

In [2]:
import pandas as pd

df = pd.read_csv(
    "../data/raw/marketing_campaign.csv",
    sep="\t"
)

df.head()

  ID\tYear_Birth\tEducation\tMarital_Status\tIncome\tKidhome\tTeenhome\tDt_Customer\tRecency\tMntWines\tMntFruits\tMntMeatProducts\tMntFishProducts\tMntSweetProducts\tMntGoldProds\tNumDealsPurchases\tNumWebPurchases\tNumCatalogPurchases\tNumStorePurchases\tNumWebVisitsMonth\tAcceptedCmp3\tAcceptedCmp4\tAcceptedCmp5\tAcceptedCmp1\tAcceptedCmp2\tComplain\tZ_CostContact\tZ_Revenue\tResponse
0  5524\t1957\tGraduation\tSingle\t58138\t0\t0\t0...
1  2174\t1954\tGraduation\tSingle\t46344\t1\t1\t0...
2  4141\t1965\tGraduation\tTogether\t71613\t0\t0\...
3  6182\t1984\tGraduation\tTogether\t26646\t1\t0\...
4  5324\t1981\tPhD\tMarried\t58293\t1\t0\t19-01-2...

In [3]:
df = pd.read_csv("../data/raw/marketing_campaign.csv", sep="\\t")

df.head()

C:\Users\Nitesh\AppData\Local\Temp\ipykernel_5052\4118447328.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df = pd.read_csv("../data/raw/marketing_campaign.csv", sep="\\t")

,"""ID",Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,"Response"""
0,"""5524",1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,"1"""
1,"""2174",1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,"0"""
2,"""4141",1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,"0"""
3,"""6182",1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,"0"""
4,"""5324",1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,"0"""

In [4]:
print(df.shape)

(2240, 29)

In [5]:
df.columns.tolist()

['"ID',
 'Year_Birth',
 'Education',
 'Marital_Status',
 'Income',
 'Kidhome',
 'Teenhome',
 'Dt_Customer',
 'Recency',
 'MntWines',
 'MntFruits',
 'MntMeatProducts',
 'MntFishProducts',
 'MntSweetProducts',
 'MntGoldProds',
 'NumDealsPurchases',
 'NumWebPurchases',
 'NumCatalogPurchases',
 'NumStorePurchases',
 'NumWebVisitsMonth',
 'AcceptedCmp3',
 'AcceptedCmp4',
 'AcceptedCmp5',
 'AcceptedCmp1',
 'AcceptedCmp2',
 'Complain',
 'Z_CostContact',
 'Z_Revenue',
 'Response"']

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   "ID                  2240 non-null   str
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   str
 3   Marital_Status       2240 non-null   str
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   str
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
 28  Response"            2240 non-null   str
dtypes: float64(1), int64(23), str(5)
memory usage: 507.6 KB

In [7]:
df.isnull().sum()

"ID                     0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response"               0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df["ID"].duplicated().sum()

KeyError: 'ID'

In [10]:
df["ID"].duplicated().sum()

KeyError: 'ID'

In [11]:
df.columns.tolist()

['"ID',
 'Year_Birth',
 'Education',
 'Marital_Status',
 'Income',
 'Kidhome',
 'Teenhome',
 'Dt_Customer',
 'Recency',
 'MntWines',
 'MntFruits',
 'MntMeatProducts',
 'MntFishProducts',
 'MntSweetProducts',
 'MntGoldProds',
 'NumDealsPurchases',
 'NumWebPurchases',
 'NumCatalogPurchases',
 'NumStorePurchases',
 'NumWebVisitsMonth',
 'AcceptedCmp3',
 'AcceptedCmp4',
 'AcceptedCmp5',
 'AcceptedCmp1',
 'AcceptedCmp2',
 'Complain',
 'Z_CostContact',
 'Z_Revenue',
 'Response"']

In [12]:
df.columns = (
    df.columns
    .str.replace('"', '', regex=False)
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
)

print(df.columns.tolist())

['id', 'year_birth', 'education', 'marital_status', 'income', 'kidhome', 'teenhome', 'dt_customer', 'recency', 'mntwines', 'mntfruits', 'mntmeatproducts', 'mntfishproducts', 'mntsweetproducts', 'mntgoldprods', 'numdealspurchases', 'numwebpurchases', 'numcatalogpurchases', 'numstorepurchases', 'numwebvisitsmonth', 'acceptedcmp3', 'acceptedcmp4', 'acceptedcmp5', 'acceptedcmp1', 'acceptedcmp2', 'complain', 'z_costcontact', 'z_revenue', 'response']

In [13]:
df[df["income"].isnull()]

,id,year_birth,education,marital_status,income,kidhome,teenhome,dt_customer,recency,mntwines,...,numwebvisitsmonth,acceptedcmp3,acceptedcmp4,acceptedcmp5,acceptedcmp1,acceptedcmp2,complain,z_costcontact,z_revenue,response
10,"""1994",1983,Graduation,Married,NaN,1,0,15-11-2013,11,5,...,7,0,0,0,0,0,0,3,11,"0"""
27,"""5255",1986,Graduation,Single,NaN,1,0,20-02-2013,19,5,...,1,0,0,0,0,0,0,3,11,"0"""
43,"""7281",1959,PhD,Single,NaN,0,0,05-11-2013,80,81,...,2,0,0,0,0,0,0,3,11,"0"""
48,"""7244",1951,Graduation,Single,NaN,2,1,01-01-2014,96,48,...,6,0,0,0,0,0,0,3,11,"0"""
58,"""8557",1982,Graduation,Single,NaN,1,0,17-06-2013,57,11,...,6,0,0,0,0,0,0,3,11,"0"""
71,"""10629",1973,2n Cycle,Married,NaN,1,0,14-09-2012,25,25,...,8,0,0,0,0,0,0,3,11,"0"""
90,"""8996",1957,PhD,Married,NaN,2,1,19-11-2012,4,230,...,9,0,0,0,0,0,0,3,11,"0"""
91,"""9235",1957,Graduation,Single,NaN,1,1,27-05-2014,45,7,...,7,0,0,0,0,0,0,3,11,"0"""
92,"""5798",1973,Master,Together,NaN,0,0,23-11-2013,87,445,...,1,0,0,0,0,0,0,3,11,"0"""
128,"""8268",1961,PhD,Married,NaN,0,1,11-07-2013,23,352,...,6,0,0,0,0,0,0,3,11,"0"""
133,"""1295",1963,Graduation,Married,NaN,0,1,11-08-2013,96,231,...,4,0,0,0,0,0,0,3,11,"0"""
312,"""2437",1989,Graduation,Married,NaN,0,0,03-06-2013,69,861,...,3,0,1,0,1,0,0,3,11,"0"""
319,"""2863",1970,Graduation,Single,NaN,1,2,23-08-2013,67,738,...,7,0,1,0,1,0,0,3,11,"0"""
1379,"""10475",1970,Master,Together,NaN,0,1,01-04-2013,39,187,...,5,0,0,0,0,0,0,3,11,"0"""
1382,"""2902",1958,Graduation,Together,NaN,1,1,03-09-2012,87,19,...,5,0,0,0,0,0,0,3,11,"0"""
1383,"""4345",1964,2n Cycle,Single,NaN,1,1,12-01-2014,49,5,...,7,0,0,0,0,0,0,3,11,"0"""
1386,"""3769",1972,PhD,Together,NaN,1,0,02-03-2014,17,25,...,7,0,0,0,0,0,0,3,11,"0"""
2059,"""7187",1969,Master,Together,NaN,1,1,18-05-2013,52,375,...,3,0,0,0,0,0,0,3,11,"0"""
2061,"""1612",1981,PhD,Single,NaN,1,0,31-05-2013,82,23,...,6,0,0,0,0,0,0,3,11,"0"""
2078,"""5079",1971,Graduation,Married,NaN,1,1,03-03-2013,82,71,...,8,0,0,0,0,0,0,3,11,"0"""
2079,"""10339",1954,Master,Together,NaN,0,1,23-06-2013,83,161,...,6,0,0,0,0,0,0,3,11,"0"""
2081,"""3117",1955,Graduation,Single,NaN,0,1,18-10-2013,95,264,...,7,0,0,0,0,0,0,3,11,"0"""
2084,"""5250",1943,Master,Widow,NaN,0,0,30-10-2013,75,532,...,1,0,0,1,0,0,0,3,11,"1"""
2228,"""8720",1978,2n Cycle,Together,NaN,0,0,12-08-2012,53,32,...,0,0,1,0,0,0,0,3,11,"0"""

In [14]:
df["income"].median()

np.float64(51381.5)

In [15]:
df["income"] = df["income"].fillna(df["income"].median())

In [16]:
df["income"] = df["income"].fillna(df["income"].median())

In [17]:
df["income"].isnull().sum()

np.int64(0)

In [18]:
df.isnull().sum()

id                     0
year_birth             0
education              0
marital_status         0
income                 0
kidhome                0
teenhome               0
dt_customer            0
recency                0
mntwines               0
mntfruits              0
mntmeatproducts        0
mntfishproducts        0
mntsweetproducts       0
mntgoldprods           0
numdealspurchases      0
numwebpurchases        0
numcatalogpurchases    0
numstorepurchases      0
numwebvisitsmonth      0
acceptedcmp3           0
acceptedcmp4           0
acceptedcmp5           0
acceptedcmp1           0
acceptedcmp2           0
complain               0
z_costcontact          0
z_revenue              0
response               0
dtype: int64

In [19]:
df.dtypes

id                         str
year_birth               int64
education                  str
marital_status             str
income                 float64
kidhome                  int64
teenhome                 int64
dt_customer                str
recency                  int64
mntwines                 int64
mntfruits                int64
mntmeatproducts          int64
mntfishproducts          int64
mntsweetproducts         int64
mntgoldprods             int64
numdealspurchases        int64
numwebpurchases          int64
numcatalogpurchases      int64
numstorepurchases        int64
numwebvisitsmonth        int64
acceptedcmp3             int64
acceptedcmp4             int64
acceptedcmp5             int64
acceptedcmp1             int64
acceptedcmp2             int64
complain                 int64
z_costcontact            int64
z_revenue                int64
response                   str
dtype: object

In [20]:
df["id"] = pd.to_numeric(df["id"], errors="coerce").astype("Int64")

In [21]:
df["id"].dtype

Int64Dtype()

In [22]:
df["dt_customer"] = pd.to_datetime(
    df["dt_customer"],
    format="%d-%m-%Y"
)

In [23]:
df["dt_customer"].dtype

dtype('<M8[us]')

In [24]:
df["response"].value_counts()

response
0"    1906
1"     334
Name: count, dtype: int64

In [25]:
df["response"] = (
    df["response"]
    .str.replace('"', '', regex=False)
    .astype(int)
)

In [26]:
df["response"].value_counts()

response
0    1906
1     334
Name: count, dtype: int64

In [27]:
df["response"].dtype

dtype('int64')

In [28]:
df["education"].value_counts()

education
Graduation    1127
PhD            486
Master         370
2n Cycle       203
Basic           54
Name: count, dtype: int64

In [29]:
df["marital_status"].value_counts()

marital_status
Married     864
Together    580
Single      480
Divorced    232
Widow        77
Alone         3
Absurd        2
YOLO          2
Name: count, dtype: int64

In [30]:
df[df["marital_status"].isin(["Alone", "Absurd", "YOLO"])]

,id,year_birth,education,marital_status,income,kidhome,teenhome,dt_customer,recency,mntwines,...,numwebvisitsmonth,acceptedcmp3,acceptedcmp4,acceptedcmp5,acceptedcmp1,acceptedcmp2,complain,z_costcontact,z_revenue,response
131,<NA>,1958,Master,Alone,61331.0,1,1,2013-03-10,42,534,...,8,0,0,0,0,0,0,3,11,0
138,<NA>,1973,PhD,Alone,35860.0,1,1,2014-05-19,37,15,...,5,1,0,0,0,0,0,3,11,1
153,<NA>,1988,Graduation,Alone,34176.0,1,0,2014-05-12,12,5,...,6,0,0,0,0,0,0,3,11,0
2093,<NA>,1993,Graduation,Absurd,79244.0,0,0,2012-12-19,58,471,...,1,0,0,1,1,0,0,3,11,1
2134,<NA>,1957,Master,Absurd,65487.0,0,0,2014-01-10,48,240,...,2,0,0,0,0,0,0,3,11,0
2177,<NA>,1973,PhD,YOLO,48432.0,0,1,2012-10-18,3,322,...,8,0,0,0,0,0,0,3,11,0
2202,<NA>,1973,PhD,YOLO,48432.0,0,1,2012-10-18,3,322,...,8,0,0,0,0,0,0,3,11,1

In [31]:
df["marital_status"] = df["marital_status"].replace(
    ["Alone", "Absurd", "YOLO"],
    "Unknown"
)

In [32]:
df["marital_status"].value_counts()

marital_status
Married     864
Together    580
Single      480
Divorced    232
Widow        77
Unknown       7
Name: count, dtype: int64

In [33]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
id,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
year_birth,2240.0,1968.805804,1893.0,1959.0,1970.0,1977.0,1996.0,11.984069
income,2240.0,52237.975446,1730.0,35538.75,51381.5,68289.75,666666.0,25037.955891
kidhome,2240.0,0.444196,0.0,0.0,0.0,1.0,2.0,0.538398
teenhome,2240.0,0.50625,0.0,0.0,0.0,1.0,2.0,0.544538
dt_customer,2240,2013-07-10 10:01:42.857142,2012-07-30 00:00:00,2013-01-16 00:00:00,2013-07-08 12:00:00,2013-12-30 06:00:00,2014-06-29 00:00:00,NaN
recency,2240.0,49.109375,0.0,24.0,49.0,74.0,99.0,28.962453
mntwines,2240.0,303.935714,0.0,23.75,173.5,504.25,1493.0,336.597393
mntfruits,2240.0,26.302232,0.0,1.0,8.0,33.0,199.0,39.773434
mntmeatproducts,2240.0,166.95,0.0,16.0,67.0,232.0,1725.0,225.715373
mntfishproducts,2240.0,37.525446,0.0,3.0,12.0,50.0,259.0,54.628979
mntsweetproducts,2240.0,27.062946,0.0,1.0,8.0,33.0,263.0,41.280498
mntgoldprods,2240.0,44.021875,0.0,9.0,24.0,56.0,362.0,52.167439
numdealspurchases,2240.0,2.325,0.0,1.0,2.0,3.0,15.0,1.932238
numwebpurchases,2240.0,4.084821,0.0,2.0,4.0,6.0,27.0,2.778714
numcatalogpurchases,2240.0,2.662054,0.0,0.0,2.0,4.0,28.0,2.923101
numstorepurchases,2240.0,5.790179,0.0,3.0,5.0,8.0,13.0,3.250958
numwebvisitsmonth,2240.0,5.316518,0.0,3.0,6.0,7.0,20.0,2.426645
acceptedcmp3,2240.0,0.072768,0.0,0.0,0.0,0.0,1.0,0.259813
acceptedcmp4,2240.0,0.074554,0.0,0.0,0.0,0.0,1.0,0.262728
acceptedcmp5,2240.0,0.072768,0.0,0.0,0.0,0.0,1.0,0.259813
acceptedcmp1,2240.0,0.064286,0.0,0.0,0.0,0.0,1.0,0.245316
acceptedcmp2,2240.0,0.013393,0.0,0.0,0.0,0.0,1.0,0.114976
complain,2240.0,0.009375,0.0,0.0,0.0,0.0,1.0,0.096391
z_costcontact,2240.0,3.0,3.0,3.0,3.0,3.0,3.0,0.0
z_revenue,2240.0,11.0,11.0,11.0,11.0,11.0,11.0,0.0
response,2240.0,0.149107,0.0,0.0,0.0,0.0,1.0,0.356274

In [34]:
df["id"].head(10)

0    <NA>
1    <NA>
2    <NA>
3    <NA>
4    <NA>
5    <NA>
6    <NA>
7    <NA>
8    <NA>
9    <NA>
Name: id, dtype: Int64

In [35]:
df["id"].isna().sum()

np.int64(2240)

In [36]:
raw_df = pd.read_csv(
    "../data/raw/marketing_campaign.csv",
    sep="\t"
)

raw_df.head()

  ID\tYear_Birth\tEducation\tMarital_Status\tIncome\tKidhome\tTeenhome\tDt_Customer\tRecency\tMntWines\tMntFruits\tMntMeatProducts\tMntFishProducts\tMntSweetProducts\tMntGoldProds\tNumDealsPurchases\tNumWebPurchases\tNumCatalogPurchases\tNumStorePurchases\tNumWebVisitsMonth\tAcceptedCmp3\tAcceptedCmp4\tAcceptedCmp5\tAcceptedCmp1\tAcceptedCmp2\tComplain\tZ_CostContact\tZ_Revenue\tResponse
0  5524\t1957\tGraduation\tSingle\t58138\t0\t0\t0...
1  2174\t1954\tGraduation\tSingle\t46344\t1\t1\t0...
2  4141\t1965\tGraduation\tTogether\t71613\t0\t0\...
3  6182\t1984\tGraduation\tTogether\t26646\t1\t0\...
4  5324\t1981\tPhD\tMarried\t58293\t1\t0\t19-01-2...

In [37]:
raw_df = pd.read_csv(
    "../data/raw/marketing_campaign.csv",
    sep="\t",
    engine="python"
)

print(raw_df.shape)
print(raw_df.columns.tolist())

(2240, 1)
['ID\tYear_Birth\tEducation\tMarital_Status\tIncome\tKidhome\tTeenhome\tDt_Customer\tRecency\tMntWines\tMntFruits\tMntMeatProducts\tMntFishProducts\tMntSweetProducts\tMntGoldProds\tNumDealsPurchases\tNumWebPurchases\tNumCatalogPurchases\tNumStorePurchases\tNumWebVisitsMonth\tAcceptedCmp3\tAcceptedCmp4\tAcceptedCmp5\tAcceptedCmp1\tAcceptedCmp2\tComplain\tZ_CostContact\tZ_Revenue\tResponse']

In [38]:
with open("../data/raw/marketing_campaign.csv", "r", encoding="utf-8") as f:
    first_data_line = f.readlines()[1]

print(repr(first_data_line[:100]))

'"5524\t1957\tGraduation\tSingle\t58138\t0\t0\t04-09-2012\t58\t635\t88\t546\t172\t88\t88\t3\t8\t10\t4\t7\t0\t0\t0\t0\t0\t0\t3\t1'

In [39]:
raw_df = pd.read_csv(
    "../data/raw/marketing_campaign.csv",
    sep=r"\t",
    engine="python",
    quotechar='"'
)

print(raw_df.shape)
print(raw_df.columns.tolist())

(2240, 29)
['"ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome', 'Teenhome', 'Dt_Customer', 'Recency', 'MntWines', 'MntFruits', 'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts', 'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases', 'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth', 'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1', 'AcceptedCmp2', 'Complain', 'Z_CostContact', 'Z_Revenue', 'Response"']

In [40]:
df = raw_df.copy()

df.columns = (
    df.columns
    .str.replace('"', '', regex=False)
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
)

print(df["id"].head())

0    "5524
1    "2174
2    "4141
3    "6182
4    "5324
Name: id, dtype: str

In [41]:
df["id"] = (
    df["id"]
    .str.replace('"', '', regex=False)
    .str.strip()
    .astype(int)
)

print(df["id"].head())
print(df["id"].dtype)

0    5524
1    2174
2    4141
3    6182
4    5324
Name: id, dtype: int64
int64

In [42]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   2240 non-null   int64
 1   year_birth           2240 non-null   int64
 2   education            2240 non-null   str
 3   marital_status       2240 non-null   str
 4   income               2216 non-null   float64
 5   kidhome              2240 non-null   int64
 6   teenhome             2240 non-null   int64
 7   dt_customer          2240 non-null   str
 8   recency              2240 non-null   int64
 9   mntwines             2240 non-null   int64
 10  mntfruits            2240 non-null   int64
 11  mntmeatproducts      2240 non-null   int64
 12  mntfishproducts      2240 non-null   int64
 13  mntsweetproducts     2240 non-null   int64
 14  mntgoldprods         2240 non-null   int64
 15  numdealspurchases    2240 non-null   int64
 16  numwebpurchases      2240 non-null   int64
 17  numcatalogpurchases  2240 non-null   int64
 18  numstorepurchases    2240 non-null   int64
 19  numwebvisitsmonth    2240 non-null   int64
 20  acceptedcmp3         2240 non-null   int64
 21  acceptedcmp4         2240 non-null   int64
 22  acceptedcmp5         2240 non-null   int64
 23  acceptedcmp1         2240 non-null   int64
 24  acceptedcmp2         2240 non-null   int64
 25  complain             2240 non-null   int64
 26  z_costcontact        2240 non-null   int64
 27  z_revenue            2240 non-null   int64
 28  response             2240 non-null   str
dtypes: float64(1), int64(24), str(4)
memory usage: 507.6 KB

In [43]:
df["income"] = df["income"].fillna(df["income"].median())

In [44]:

df["income"].isnull().sum()

np.int64(0)

In [45]:
df["dt_customer"] = pd.to_datetime(
    df["dt_customer"],
    format="%d-%m-%Y"
)

In [46]:
df["dt_customer"].dtype

dtype('<M8[us]')

In [47]:
df["response"] = (
    df["response"]
    .str.replace('"', '', regex=False)
    .str.strip()
    .astype(int)
)

In [48]:
df["response"].value_counts()

response
0    1906
1     334
Name: count, dtype: int64

In [49]:
df.isnull().sum()

id                     0
year_birth             0
education              0
marital_status         0
income                 0
kidhome                0
teenhome               0
dt_customer            0
recency                0
mntwines               0
mntfruits              0
mntmeatproducts        0
mntfishproducts        0
mntsweetproducts       0
mntgoldprods           0
numdealspurchases      0
numwebpurchases        0
numcatalogpurchases    0
numstorepurchases      0
numwebvisitsmonth      0
acceptedcmp3           0
acceptedcmp4           0
acceptedcmp5           0
acceptedcmp1           0
acceptedcmp2           0
complain               0
z_costcontact          0
z_revenue              0
response               0
dtype: int64

In [50]:
df["year_birth"].value_counts().sort_index().head(15)

year_birth
1893     1
1899     1
1900     1
1940     1
1941     1
1943     7
1944     7
1945     8
1946    16
1947    16
1948    21
1949    30
1950    29
1951    43
1952    52
Name: count, dtype: int64

In [51]:
df[df["year_birth"] < 1940][["id", "year_birth", "income"]].head(20)

        id  year_birth   income
192   7829        1900  36640.0
239  11004        1893  60182.0
339   1150        1899  83532.0

In [52]:
df.loc[df["year_birth"] < 1940, "year_birth"] = pd.NA

In [53]:
df[df["year_birth"].isna()][["id", "year_birth", "income"]]

        id  year_birth   income
192   7829         NaN  36640.0
239  11004         NaN  60182.0
339   1150         NaN  83532.0

In [54]:
df["year_birth"].median()

np.float64(1970.0)

In [55]:
df["year_birth"] = df["year_birth"].fillna(df["year_birth"].median())

In [56]:
df["year_birth"].isnull().sum()

np.int64(0)

In [57]:
df["year_birth"].min()

np.float64(1940.0)

In [58]:
print("Kidhome:", sorted(df["kidhome"].unique()))
print("Teenhome:", sorted(df["teenhome"].unique()))

Kidhome: [np.int64(0), np.int64(1), np.int64(2)]
Teenhome: [np.int64(0), np.int64(1), np.int64(2)]

In [59]:
purchase_cols = [
    "numdealspurchases",
    "numwebpurchases",
    "numcatalogpurchases",
    "numstorepurchases",
    "numwebvisitsmonth"
]

df[purchase_cols].min()

numdealspurchases      0
numwebpurchases        0
numcatalogpurchases    0
numstorepurchases      0
numwebvisitsmonth      0
dtype: int64

In [60]:
binary_cols = [
    "acceptedcmp1",
    "acceptedcmp2",
    "acceptedcmp3",
    "acceptedcmp4",
    "acceptedcmp5",
    "complain",
    "response"
]

for col in binary_cols:
    print(col, sorted(df[col].unique()))

acceptedcmp1 [np.int64(0), np.int64(1)]
acceptedcmp2 [np.int64(0), np.int64(1)]
acceptedcmp3 [np.int64(0), np.int64(1)]
acceptedcmp4 [np.int64(0), np.int64(1)]
acceptedcmp5 [np.int64(0), np.int64(1)]
complain [np.int64(0), np.int64(1)]
response [np.int64(0), np.int64(1)]

In [61]:
spending_cols = [
    "mntwines",
    "mntfruits",
    "mntmeatproducts",
    "mntfishproducts",
    "mntsweetproducts",
    "mntgoldprods"
]

df[spending_cols].min()

mntwines            0
mntfruits           0
mntmeatproducts     0
mntfishproducts     0
mntsweetproducts    0
mntgoldprods        0
dtype: int64

In [62]:
df[df["income"] == df["income"].max()][
    ["id", "year_birth", "education", "marital_status", "income"]
]

        id  year_birth   education marital_status    income
2233  9432      1977.0  Graduation       Together  666666.0

In [63]:
df["id"].duplicated().sum()

np.int64(0)

In [64]:
print("Rows and Columns:", df.shape)
print("Missing Values:", df.isnull().sum().sum())
print("Duplicate Rows:", df.duplicated().sum())

Rows and Columns: (2240, 29)
Missing Values: 0
Duplicate Rows: 0

In [65]:
df.dtypes

id                              int64
year_birth                    float64
education                         str
marital_status                    str
income                        float64
kidhome                         int64
teenhome                        int64
dt_customer            datetime64[us]
recency                         int64
mntwines                        int64
mntfruits                       int64
mntmeatproducts                 int64
mntfishproducts                 int64
mntsweetproducts                int64
mntgoldprods                    int64
numdealspurchases               int64
numwebpurchases                 int64
numcatalogpurchases             int64
numstorepurchases               int64
numwebvisitsmonth               int64
acceptedcmp3                    int64
acceptedcmp4                    int64
acceptedcmp5                    int64
acceptedcmp1                    int64
acceptedcmp2                    int64
complain                        int64
z_costcontact                   int64
z_revenue                       int64
response                        int64
dtype: object

In [66]:
df["year_birth"] = df["year_birth"].astype(int)

In [67]:
df["year_birth"].dtype

dtype('int64')

In [68]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   2240 non-null   int64
 1   year_birth           2240 non-null   int64
 2   education            2240 non-null   str
 3   marital_status       2240 non-null   str
 4   income               2240 non-null   float64
 5   kidhome              2240 non-null   int64
 6   teenhome             2240 non-null   int64
 7   dt_customer          2240 non-null   datetime64[us]
 8   recency              2240 non-null   int64
 9   mntwines             2240 non-null   int64
 10  mntfruits            2240 non-null   int64
 11  mntmeatproducts      2240 non-null   int64
 12  mntfishproducts      2240 non-null   int64
 13  mntsweetproducts     2240 non-null   int64
 14  mntgoldprods         2240 non-null   int64
 15  numdealspurchases    2240 non-null   int64
 16  numwebpurchases      2240 non-null   int64
 17  numcatalogpurchases  2240 non-null   int64
 18  numstorepurchases    2240 non-null   int64
 19  numwebvisitsmonth    2240 non-null   int64
 20  acceptedcmp3         2240 non-null   int64
 21  acceptedcmp4         2240 non-null   int64
 22  acceptedcmp5         2240 non-null   int64
 23  acceptedcmp1         2240 non-null   int64
 24  acceptedcmp2         2240 non-null   int64
 25  complain             2240 non-null   int64
 26  z_costcontact        2240 non-null   int64
 27  z_revenue            2240 non-null   int64
 28  response             2240 non-null   int64
dtypes: datetime64[us](1), float64(1), int64(25), str(2)
memory usage: 507.6 KB

In [69]:
df.head()

,id,year_birth,education,marital_status,income,kidhome,teenhome,dt_customer,recency,mntwines,...,numwebvisitsmonth,acceptedcmp3,acceptedcmp4,acceptedcmp5,acceptedcmp1,acceptedcmp2,complain,z_costcontact,z_revenue,response
0,5524,1957,Graduation,Single,58138.0,0,0,2012-09-04,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,2014-03-08,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,2013-08-21,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,2014-02-10,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,2014-01-19,94,173,...,5,0,0,0,0,0,0,3,11,0

In [70]:
df.to_csv("../data/processed/marketing_campaign_cleaned.csv", index=False)

In [71]:
import os

os.path.exists("../data/processed/marketing_campaign_cleaned.csv")

True